### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by wheemyungshin**
tpu dir uploaded

### CODE REVIEW

**Review by kairos03 — CHANGES_REQUESTED** [review]
How to run your code?

**Comment by wheemyungshin** [comment]
> How to run your code?
I'll upload .sh files too

**Review by kairos03 — APPROVED** [review]

**Comment by kairos03** [comment]
how to run without tpu? @wheemyungshin

**Comment by wheemyungshin** [comment]
> how to run without tpu? @wheemyungshin
it runs with gpu automatically if no tpu is allocated using --tpu

Also, not all scripts are uploaded yet

**Comment by kairos03** [comment]
then create new pull request and upload all scripts.

**Pull request merged**
